language: php

php:
  - 7.0

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update 1.2.2 && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.2.0"
  - travis_retry composer update --dev --prefer-dist --no-interaction
# setup application:
  - |
    php init --env=Development --overwrite=n
    sed -i s/root/travis/ common/config/main-local.php
    sed -i "s/'cookieValidationKey' => ''/'cookieValidationKey' => 'testkey'/" application/config/main.php

before_script:
  - mysql -e 'CREATE DATABASE yii2_template_test;'
  - php yii_test migrate --interactive=0

script:
  - composer validate --strict
  - composer exec codecept run
